"""
Wrap an existing per_fact_report.csv with bootstrap 95% CIs.

This script does NOT re-run the LLM benchmark. It re-aggregates the scores
that are already in reports/per_fact_report.csv and reports point estimates
alongside non-parametric percentile-bootstrap confidence intervals.

Why: a point estimate like "composite_stability = 0.593" is not publishable
on its own — at N = 29 facts the sampling variance is non-trivial. See
docs/STATISTICAL_RIGOR.md for the methodology rationale and the
fact-level vs group-level resampling discussion.

Usage
-----
    # Typical case: use the CSV generated by `python report.py`:
    python evaluate_with_ci.py reports/per_fact_report.csv

    # Bootstrap more iterations for tighter CI estimates:
    python evaluate_with_ci.py reports/per_fact_report.csv --bootstrap 20000

    # Only a specific metric:
    python evaluate_with_ci.py reports/per_fact_report.csv --metric hallucination_rate

    # Emit a summary CSV alongside the console output:
    python evaluate_with_ci.py reports/per_fact_report.csv --output reports/ci_summary.csv

Design notes
------------
- Resampling unit is FACT, not group. Groups within a fact share the same
  ground truth and the same source report; they are not independent, and
  treating them as such would produce artificially narrow CIs.
- We also emit the group-level CI (resampling each row independently) as
  a secondary number, so the reader can see how much of the variance is
  within-fact (template/temperature noise) vs across-fact (which facts
  the model happens to be good or bad at).
- Percentile-bootstrap, not BCa, for simplicity and readability. For the
  sample sizes and bounded metrics in this benchmark the bias correction
  is small and not worth the code complexity.
- Seeded RNG via --seed so results are reproducible.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd

# Metrics we know how to summarise. All are bounded in [0, 1] and are
# stored per-row in per_fact_report.csv.
DEFAULT_METRICS: Tuple[str, ...] = (
    "composite_stability",
    "semantic_score",
    "factual_score",
    "hallucination_rate",
    "extraction_failure_rate",
)


def _fact_level_mean(df: pd.DataFrame, metric: str) -> float:
    """Collapse (template, temperature) rows to one number per fact, then mean.

    Equal weight per fact, not per group. A fact that has more groups
    (e.g. because of retries in the pipeline) must not double-count.
    """
    per_fact = df.groupby("fact_id")[metric].mean()
    return float(per_fact.mean())


def _bootstrap_ci(
    values: np.ndarray,
    n_iter: int,
    alpha: float,
    rng: np.random.Generator,
) -> Tuple[float, float]:
    """Percentile-bootstrap 95% CI of the mean of `values`.

    Parameters
    ----------
    values : np.ndarray
        The 1-D array of units being resampled.
    n_iter : int
        Bootstrap iteration count.
    alpha : float
        Two-sided significance level (0.05 for 95% CI).
    rng : np.random.Generator
        Seeded RNG for reproducibility.
    """
    n = len(values)
    if n == 0:
        return (float("nan"), float("nan"))
    # Vectorised resampling: n_iter x n index matrix, take mean per row.
    idx = rng.integers(low=0, high=n, size=(n_iter, n))
    resampled_means = values[idx].mean(axis=1)
    lo = float(np.percentile(resampled_means, 100 * alpha / 2))
    hi = float(np.percentile(resampled_means, 100 * (1 - alpha / 2)))
    return (lo, hi)


def bootstrap_fact_level(
    df: pd.DataFrame,
    metric: str,
    n_iter: int,
    alpha: float,
    rng: np.random.Generator,
) -> Tuple[float, float, float, int]:
    """Resample facts (one mean per fact) with replacement.

    Returns (point, ci_lower, ci_upper, n_facts).
    """
    per_fact = df.groupby("fact_id")[metric].mean().to_numpy()
    point = float(per_fact.mean())
    lo, hi = _bootstrap_ci(per_fact, n_iter, alpha, rng)
    return point, lo, hi, int(len(per_fact))


def bootstrap_group_level(
    df: pd.DataFrame,
    metric: str,
    n_iter: int,
    alpha: float,
    rng: np.random.Generator,
) -> Tuple[float, float, float, int]:
    """Resample groups (one row per [fact, template, temperature]) with replacement.

    Returns (point, ci_lower, ci_upper, n_groups).
    """
    vals = df[metric].to_numpy()
    point = float(vals.mean())
    lo, hi = _bootstrap_ci(vals, n_iter, alpha, rng)
    return point, lo, hi, int(len(vals))


def _format_row(
    metric: str,
    fact_point: float,
    fact_lo: float,
    fact_hi: float,
    n_facts: int,
    grp_point: float,
    grp_lo: float,
    grp_hi: float,
    n_groups: int,
) -> str:
    return (
        f"{metric}\n"
        f"  fact-level  : {fact_point:.4f}   95% CI [{fact_lo:.4f}, {fact_hi:.4f}]   (N_facts = {n_facts})\n"
        f"  group-level : {grp_point:.4f}   95% CI [{grp_lo:.4f}, {grp_hi:.4f}]   (N_groups = {n_groups})\n"
    )


def _validate_csv(df: pd.DataFrame, metrics: Iterable[str]) -> None:
    """Surface missing-column issues with an actionable error message."""
    if "fact_id" not in df.columns:
        raise SystemExit(
            "Input CSV is missing the 'fact_id' column. "
            "Make sure you are pointing at reports/per_fact_report.csv "
            "(or a CSV with the same schema)."
        )
    missing = [m for m in metrics if m not in df.columns]
    if missing:
        available = ", ".join(sorted(c for c in df.columns if c not in {"fact_id"}))
        raise SystemExit(
            f"Input CSV is missing metric columns {missing}. "
            f"Available numeric-looking columns: {available}"
        )


def run(args: argparse.Namespace) -> int:
    rng = np.random.default_rng(args.seed)

    csv_path = Path(args.csv)
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")

    # per_fact_report.csv is written with '#'-prefixed comment headers;
    # pandas handles that via `comment="#"`.
    df = pd.read_csv(csv_path, comment="#")

    metrics: List[str] = [args.metric] if args.metric else list(DEFAULT_METRICS)
    _validate_csv(df, metrics)

    # Console header.
    print("=" * 72)
    print("  Bootstrap 95% CIs over per_fact_report.csv")
    print("=" * 72)
    print(f"Input file         : {csv_path}")
    print(f"Bootstrap iter     : {args.bootstrap}")
    print(f"Random seed        : {args.seed}")
    print(f"Alpha (two-sided)  : {args.alpha}")
    print("Resampling unit    : fact (primary) and group (secondary)")
    print("")

    out_rows: List[Dict[str, object]] = []
    for metric in metrics:
        fact_point, fact_lo, fact_hi, n_facts = bootstrap_fact_level(
            df,
            metric,
            args.bootstrap,
            args.alpha,
            rng,
        )
        grp_point, grp_lo, grp_hi, n_groups = bootstrap_group_level(
            df,
            metric,
            args.bootstrap,
            args.alpha,
            rng,
        )
        print(
            _format_row(
                metric,
                fact_point,
                fact_lo,
                fact_hi,
                n_facts,
                grp_point,
                grp_lo,
                grp_hi,
                n_groups,
            )
        )
        out_rows.append(
            {
                "metric": metric,
                "fact_point": round(fact_point, 6),
                "fact_ci_lower": round(fact_lo, 6),
                "fact_ci_upper": round(fact_hi, 6),
                "n_facts": n_facts,
                "group_point": round(grp_point, 6),
                "group_ci_lower": round(grp_lo, 6),
                "group_ci_upper": round(grp_hi, 6),
                "n_groups": n_groups,
            }
        )

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(out_rows[0].keys()))
            writer.writeheader()
            writer.writerows(out_rows)
        print(f"Wrote summary CSV: {out_path}")

    print("-" * 72)
    print(
        "Interpretation:\n"
        "  * Fact-level CI is the primary number to cite — it treats each\n"
        "    financial fact as one unit and resamples with replacement.\n"
        "  * Group-level CI is narrower because it treats each (template,\n"
        "    temperature) row as an independent observation. It understates\n"
        "    true uncertainty and should not be used for model-to-model\n"
        "    comparison. It is shown here only to surface how much of the\n"
        "    variance is within-fact noise.\n"
        "  * See docs/STATISTICAL_RIGOR.md for why this distinction matters."
    )
    print("=" * 72)
    return 0


def _parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bootstrap 95% CIs for metrics in per_fact_report.csv.",
    )
    parser.add_argument(
        "csv",
        help="Path to per_fact_report.csv (output of python report.py).",
    )
    parser.add_argument(
        "--bootstrap",
        type=int,
        default=10000,
        help="Bootstrap iteration count (default: 10000).",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Two-sided significance level (default: 0.05 for a 95%% CI).",
    )
    parser.add_argument(
        "--metric",
        type=str,
        default=None,
        help="Single metric to summarise (default: all known metrics).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed for the numpy RNG (default: 42).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional path to write a summary CSV (one row per metric).",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    sys.exit(run(_parse_args(sys.argv[1:])))
